### ISSUE TITLE
Couldn't help noticing taskrabbit/empujar

### ISSUE THREAD

**Issue by olalonde** [taskrabbit/empujar#5]
and was just curious why you have two very similar tools, one in Ruby (https://github.com/taskrabbit/forklift) and the other in Node.js. Which one came first and why did you decide to write the other?

**Comment by evantahler** [comment]
Hi!

The [ruby project](https://github.com/taskrabbit/forklift) came first, and is the spiritual ancestor to this project.  TaskRabbit was mostly a ruby shop back then, so that's where it made sense to start.  Then, as time went, we kept adding things to to the tool: more transports, more complex logic, etc, and Forklift was getting messy.  Some of the patterns were too rigid, email probably shouldn't have been built into the project, etc.  Not only did the tool need a "cleanup pass", but it also needed a "speed" pass.  

Assuming most of the in-thread transformations you might want to do are low-CPU, the async-ness of node actually makes is a wonderful candidate for streaming data... the primary use-case of an ETL tool. The streams/emitter style of programming works really well here, and let us come up with (what I feel are) some pretty good programming patterns.  [This example](https://github.com/taskrabbit/empujar/blob/master/books/etl/chapters/extract%2Bload/extract.js) is a good sample, as it shows how you can steam `n` tables (`threads = 5`) out of mySQL in parallel.

We also discovered that the patterns we came up with work great for other streaming jobs as well.  For example, we we use Empujar to stream FTP files from our telephony provider into S3 every hour... and we can do a bunch of those jobs in parallel as well.  It's just another "book".

At some point, we'll get to [multi-server parallelism](https://github.com/taskrabbit/empujar/issues/2), and this tool will really fly :D

**Comment by evantahler** [comment]
I should also call out that while @taskrabbit doesn't use Forklift anymore, there are some other folks still working on the project, like @rgarver and the team at @InternMatch

**Comment by olalonde** [comment]
@evantahler thanks for the answer, makes sense. looking forward to try empujar soon 👍
